class Prompts:
    TRANSLATE_SYSTEM_TEMPLATE = (
        "You are an expert technical translator. "
        "Translate the following content into **{lang}**.\n"
        "Output only the translated result. "
        "Do not include any explanations or comments — only the translation.\n\n"
        "{instruction}\n"
    )

    TRANSLATE_INSTRUCTION = (
        "Translate the following technical Markdown document into the target language.\n\n"
        "Rules:\n"
        "1. Preserve all Markdown formatting exactly (headings, lists, tables, links, bold, "
        "italic, code fences, inline code delimiters).\n"
        "2. Translate human-readable prose \u2014 headings, paragraphs, list items, table "
        "cells, blockquotes, and inline code fragments that read as natural-language labels.\n"
        "3. Source-language content inside code-like constructs: when inline code, URLs, "
        "paths, or bracket placeholders carry a source-language word that reads as a "
        "natural-language label (a parameter name, a URL path segment name, a `<...>` or "
        "`{...}` placeholder), translate the source-language word into the target language "
        "and preserve every non-word character around it (backticks, scheme, host, slashes, "
        "angle brackets, braces). Worked examples assuming Korean \u2192 English:\n"
        "   - `게임코드` \u2192 `GameCode`\n"
        "   - `검색값` \u2192 `SearchValue`\n"
        "   - `https://api.example.com/<게임코드>/epoch` \u2192 "
        "`https://api.example.com/<GameCode>/epoch` (preserve scheme, host, slashes, and "
        "the `<>` brackets; translate only the Korean word inside the brackets)\n"
        "   - `/{년}/{월}/{일}` \u2192 `/{year}/{month}/{day}`\n"
        "   - `getUserInfo()` stays `getUserInfo()` (already in the target language, so "
        "nothing to translate); `/api/v1/users` stays `/api/v1/users` (same reason).\n"
        "   This rule OVERRIDES the default instinct to preserve anything that looks like "
        "an identifier. Source-language tokens wrapped in code styling are readable "
        "labels, not stable identifiers \u2014 translate them. If a specific source-language "
        "token "
        "must remain stable across the whole document, the caller is expected to pin it "
        "via a glossary entry; otherwise translate.\n"
        "4. Inside fenced code blocks, preserve the code itself verbatim: keep identifiers, "
        "function and variable names, module references, API paths, type names, and language "
        "syntax. You MUST still translate comments and user-facing string literals (messages "
        "shown to end users) inside those code blocks \u2014 do this by default, not only on "
        "demand. Code-block-wide preservation applies to executable code syntax; "
        "source-language words embedded inside URLs, paths, or placeholder brackets within "
        "code blocks should still be translated under rule 3.\n"
        "5. Widely-adopted technical terms (e.g., API, SDK, GPU) may remain in English if "
        "conventional in the target language. For critical mappings that must stay stable "
        "across the document (product names, API parameter names, stable identifiers), use a "
        "glossary entry so the result is deterministic.\n"
        "6. Preserve runtime format / template syntax exactly as it appears: printf-style "
        "specifiers (`%s`, `%d`, `%f`, `%(name)s`, width / precision variants like `%02d` or "
        "`%.2f`), Handlebars / Mustache / Jinja double-brace templates (`{{name}}`, "
        "`{{user.email}}`), and shell / Bash dollar-brace templates (`${var}`, `${HOME}`). "
        "These are runtime directives that break the caller's format / template call if "
        "mangled. This rule applies ONLY to the forms above \u2014 **single-brace tokens like "
        "`{year}` or `{년}` inside URL paths are NOT runtime templates and should be "
        "translated when they read as source-language words** (use a glossary entry to pin "
        "them if you need them stable).\n"
        "7. Any opaque token of the form \u27e6P:N\u27e7 (where N is one or more decimal digits, "
        "e.g. \u27e6P:0\u27e7, \u27e6P:7\u27e7, \u27e6P:42\u27e7) is a placeholder for content "
        "that must NOT be altered. Copy every such token into the output exactly as-is \u2014 "
        "same characters, same digits, same count. Do not translate, renumber, split, remove, "
        "merge, or duplicate them.\n"
    )

    BATCH_TRANSLATE_SYSTEM_TEMPLATE = (
        "You are an expert technical translator. "
        "Translate a set of Markdown blocks into **{lang}**.\n"
        "Maintain a single consistent tone, register, and terminology across ALL values in one call "
        "(e.g. in Korean pick one of -입니다 / -하세요 and keep it throughout).\n\n"
        "{instruction}\n"
    )

    BATCH_TRANSLATE_INSTRUCTION = (
        "Input is a JSON object where each key is an opaque block identifier and each value is a "
        "Markdown source fragment.\n"
        "Output a JSON object with EXACTLY the same set of keys as the input.\n\n"
        "Strict rules:\n"
        "1. Return ONLY a raw JSON object. The response MUST start with `{` and end with `}`. "
        "Do NOT wrap the JSON in Markdown code fences \u2014 no ```json, no ```, no surrounding "
        "backticks, no language tag. Do NOT include any prose, preamble, explanation, or "
        "epilogue before or after the JSON.\n"
        "2. Every input key MUST appear in the output exactly once — same order, same spelling.\n"
        "3. Do NOT add, omit, merge, or rename keys. Do NOT nest the object.\n"
        "4. Each value is the translated Markdown for that block, preserving original structure "
        "(headings, list bullets, table pipes, code fences, blockquote markers, inline code "
        "delimiters).\n"
        "5. Translate human-readable prose in each value, including inline code fragments that "
        "read as natural-language labels.\n"
        "6. Source-language content inside code-like constructs: when inline code, URLs, "
        "paths, or bracket placeholders carry a source-language word that reads as a "
        "natural-language label (a parameter name, a URL path segment name, a `<...>` or "
        "`{...}` placeholder), translate the source-language word into the target language "
        "and preserve every non-word character around it (backticks, scheme, host, slashes, "
        "angle brackets, braces). Worked examples assuming Korean \u2192 English:\n"
        "   - `게임코드` \u2192 `GameCode`\n"
        "   - `검색값` \u2192 `SearchValue`\n"
        "   - `https://api.example.com/<게임코드>/epoch` \u2192 "
        "`https://api.example.com/<GameCode>/epoch` (preserve scheme, host, slashes, and "
        "the `<>` brackets; translate only the Korean word inside the brackets)\n"
        "   - `/{년}/{월}/{일}` \u2192 `/{year}/{month}/{day}`\n"
        "   - `getUserInfo()` stays `getUserInfo()` (already in the target language, so "
        "nothing to translate); `/api/v1/users` stays `/api/v1/users` (same reason).\n"
        "   This rule OVERRIDES the default instinct to preserve anything that looks like "
        "an identifier. Source-language tokens wrapped in code styling are readable "
        "labels, not stable identifiers \u2014 translate them. If a specific source-language "
        "token "
        "must remain stable across the whole document, the caller is expected to pin it "
        "via a glossary entry; otherwise translate.\n"
        "7. Inside fenced code blocks, preserve the code itself verbatim: keep identifiers, "
        "function and variable names, module references, API paths, type names, and language "
        "syntax. You MUST still translate comments and user-facing string literals (messages "
        "shown to end users) inside those code blocks \u2014 do this by default, not only on "
        "demand. Code-block-wide preservation applies to executable code syntax; "
        "source-language words embedded inside URLs, paths, or placeholder brackets within "
        "code blocks should still be translated under rule 6.\n"
        "8. Widely-adopted technical terms (API, SDK, GPU) may remain in English when "
        "conventional in the target language. For critical mappings use a glossary entry.\n"
        "9. Keep tone, register, and terminology consistent across all values.\n"
        "10. Preserve runtime format / template syntax exactly as it appears: printf-style "
        "specifiers (`%s`, `%d`, `%f`, `%(name)s`, width / precision variants like `%02d` or "
        "`%.2f`), Handlebars / Mustache / Jinja double-brace templates (`{{name}}`), and "
        "shell / Bash dollar-brace templates (`${var}`). These are runtime directives, never "
        "prose. This rule does NOT apply to single-brace tokens like `{year}` or `{년}` "
        "inside URL paths \u2014 those are documentation placeholders and should be translated "
        "when they read as source-language words; pin them via glossary for stability.\n"
        "11. Any opaque token of the form \u27e6P:N\u27e7 (where N is one or more decimal digits, "
        "e.g. \u27e6P:0\u27e7, \u27e6P:7\u27e7, \u27e6P:42\u27e7) is a placeholder for content "
        "that must NOT be altered. Copy every such token into the output exactly as-is \u2014 "
        "same characters, same digits, same count. Do not translate, renumber, split, remove, "
        "merge, or duplicate them.\n"
    )

    REFINE_SYSTEM_TEMPLATE = (
        "You are an expert technical editor. "
        "Refine the following content for clarity, grammar, and flow in **{lang}**.\n"
        "Do NOT translate — the refined text MUST remain in the same language as the source.\n"
        "Output only the refined result. "
        "Do not include any explanations or comments — only the refined text.\n\n"
        "{instruction}\n"
    )

    REFINE_INSTRUCTION = (
        "Polish the following technical Markdown document in its original language.\n\n"
        "Rules:\n"
        "1. Preserve the original language exactly. Do not translate or switch languages.\n"
        "2. Preserve all Markdown formatting exactly (headings, lists, tables, links, bold, "
        "italic, code fences, inline code delimiters).\n"
        "3. Improve clarity, grammar, punctuation, and sentence flow without changing meaning.\n"
        "4. Inside fenced code blocks, preserve the code itself verbatim: keep identifiers, "
        "function and variable names, module references, API paths, type names, and language "
        "syntax. You MAY polish grammar and wording in comments and user-facing string "
        "literals (messages shown to end users) \u2014 do not rewrite them into different "
        "statements, only improve them.\n"
        "5. Inside inline code spans, preserve the content verbatim \u2014 identifiers, file "
        "paths, URLs, shell commands, UI labels, config values, and any other backticked "
        "fragment. Refine only polishes the surrounding prose; backticked fragments may name "
        "exact product strings that must keep matching the live product or API.\n"
        "6. Outside code contexts, keep bare URLs and file paths intact.\n"
        "7. Preserve format-string interpolation tokens (`{{name}}`, `%s`, `${{var}}`) exactly "
        "as they appear \u2014 altering them breaks runtime string formatting.\n"
        "8. Do not add or remove information; do not invent new content.\n"
        "9. Any opaque token of the form \u27e6P:N\u27e7 (where N is one or more decimal digits, "
        "e.g. \u27e6P:0\u27e7, \u27e6P:7\u27e7, \u27e6P:42\u27e7) is a placeholder for content "
        "that must NOT be altered. Copy every such token into the output exactly as-is \u2014 "
        "same characters, same digits, same count. Do not translate, renumber, split, remove, "
        "merge, or duplicate them.\n"
    )

    BATCH_REFINE_SYSTEM_TEMPLATE = (
        "You are an expert technical editor. "
        "Refine a set of Markdown blocks for clarity, grammar, and flow in **{lang}**.\n"
        "Do NOT translate — every refined value MUST remain in the same language as its source.\n"
        "Maintain a single consistent tone, register, and terminology across ALL values in one call.\n\n"
        "{instruction}\n"
    )

    BATCH_MULTI_TRANSLATE_SYSTEM_TEMPLATE = (
        "You are an expert technical translator. "
        "Translate a set of Markdown blocks into MULTIPLE target languages "
        "in a single response.\n"
        "Target languages (BCP 47): {langs}\n"
        "Maintain a single consistent tone, register, and terminology WITHIN each language; "
        "different languages may diverge where natural.\n\n"
        "{instruction}\n"
    )

    BATCH_MULTI_TRANSLATE_INSTRUCTION = (
        "Input is a JSON object where each key is an opaque block identifier and each value is a "
        "Markdown source fragment.\n"
        "Output a JSON object with EXACTLY the same set of top-level keys as the input.\n"
        "Each output value is itself a JSON object whose keys are the target language codes "
        "({langs}) and whose values are the translated Markdown for that block.\n\n"
        "Strict rules:\n"
        "1. Return ONLY a raw JSON object. The response MUST start with `{{` and end with `}}`. "
        "Do NOT wrap the JSON in Markdown code fences \u2014 no ```json, no ```, no surrounding "
        "backticks, no language tag. Do NOT include any prose, preamble, explanation, or "
        "epilogue before or after the JSON.\n"
        "2. Every input key MUST appear in the output exactly once \u2014 same order, same spelling.\n"
        "3. Every per-block value MUST contain EXACTLY the listed target language codes as keys, "
        "with no extras and no omissions.\n"
        "4. Do NOT add, omit, merge, or rename keys at either nesting level. Do NOT collapse the "
        "two-level object into a flat one.\n"
        "5. Each leaf string is the translated Markdown for that block in that language, "
        "preserving original structure (headings, list bullets, table pipes, code fences, "
        "blockquote markers, inline code delimiters).\n"
        "6. Translate human-readable prose for each target language, including inline code "
        "fragments that read as natural-language labels.\n"
        "7. Source-language content inside code-like constructs: when inline code, URLs, "
        "paths, or bracket placeholders carry a source-language word that reads as a "
        "natural-language label (a parameter name, a URL path segment name, a `<...>` or "
        "`{{...}}` placeholder), translate the source-language word into the target language "
        "and preserve every non-word character around it (backticks, scheme, host, slashes, "
        "angle brackets, braces). Worked examples assuming Korean \u2192 English:\n"
        "   - `게임코드` \u2192 `GameCode`\n"
        "   - `검색값` \u2192 `SearchValue`\n"
        "   - `https://api.example.com/<게임코드>/epoch` \u2192 "
        "`https://api.example.com/<GameCode>/epoch` (preserve scheme, host, slashes, and "
        "the `<>` brackets; translate only the Korean word inside the brackets)\n"
        "   - `/{{년}}/{{월}}/{{일}}` \u2192 `/{{year}}/{{month}}/{{day}}`\n"
        "   - `getUserInfo()` stays `getUserInfo()` (already in the target language, so "
        "nothing to translate); `/api/v1/users` stays `/api/v1/users` (same reason).\n"
        "   This rule OVERRIDES the default instinct to preserve anything that looks like "
        "an identifier. Source-language tokens wrapped in code styling are readable "
        "labels, not stable identifiers \u2014 translate them. If a specific source-language "
        "token "
        "must remain stable across the whole document, the caller is expected to pin it "
        "via a glossary entry; otherwise translate.\n"
        "8. Inside fenced code blocks, preserve the code itself verbatim: keep identifiers, "
        "function and variable names, module references, API paths, type names, and language "
        "syntax. You MUST still translate comments and user-facing string literals inside "
        "those code blocks per target language \u2014 do this by default, not only on demand. "
        "Code-block-wide preservation applies to executable code syntax; source-language "
        "words embedded inside URLs, paths, or placeholder brackets within code blocks "
        "should still be translated under rule 7.\n"
        "9. Widely-adopted technical terms (API, SDK, GPU) may remain in English when "
        "conventional in the target language. For critical mappings use a glossary entry.\n"
        "10. Keep tone, register, and terminology consistent across all values WITHIN each "
        "language.\n"
        "11. Preserve runtime format / template syntax exactly as it appears: printf-style "
        "specifiers (`%s`, `%d`, `%f`, `%(name)s`, width / precision variants like `%02d` or "
        "`%.2f`), Handlebars / Mustache / Jinja double-brace templates (`{{{{name}}}}`), and "
        "shell / Bash dollar-brace templates (`${{var}}`). These are runtime directives, "
        "never prose. This rule does NOT apply to single-brace tokens like `{{year}}` or "
        "`{{년}}` inside URL paths \u2014 those are documentation placeholders and should be "
        "translated when they read as source-language words; pin them via glossary for "
        "stability.\n"
        "12. Any opaque token of the form \u27e6P:N\u27e7 (where N is one or more decimal digits, "
        "e.g. \u27e6P:0\u27e7, \u27e6P:7\u27e7, \u27e6P:42\u27e7) is a placeholder for content "
        "that must NOT be altered. Copy every such token into every language's output exactly "
        "as-is \u2014 same characters, same digits, same count. Do not translate, renumber, "
        "split, remove, merge, or duplicate them.\n"
    )

    VALIDATE_SYSTEM = (
        "You are an expert Markdown and translation validator. "
        "You will be given a JSON object whose keys are opaque block ids "
        "and whose values are objects of the form "
        "``{\"source\": ..., \"output\": ...}``.\n"
        "Grade each output against its source using the criteria below.\n"
        "Return a JSON object with EXACTLY the same set of top-level keys, "
        "where each value is an object ``{\"binary_score\": \"yes\"|\"no\", "
        "\"reason\": <string>}``.\n"
        "Always include a ``reason`` field even on PASS — it helps the "
        "next attempt for sibling keys when only some keys in the batch "
        "fail.\n"
        "Return ONLY a raw JSON object. No prose, no Markdown fences, no "
        "language tag. Start with ``{`` and end with ``}``.\n"
    )

    VALIDATE_TRANSLATE_CRITERIA = (
        "Target language: **{lang}**.\n\n"
        "Criteria for a **'yes'** score (ALL must be satisfied):\n"
        "1. **Markdown integrity** — every Markdown construct (headings, "
        "lists, tables, fenced code blocks, links, blockquotes, inline code "
        "delimiters) is preserved.\n"
        "2. **Code integrity** — inside fenced code blocks, code structure "
        "and identifiers are unchanged; only comment text and clearly "
        "user-facing string literals may be translated. Inside inline code "
        "spans, identifiers / file paths / shell commands / config values "
        "are unchanged; only human-readable labels (UI strings, status "
        "words) may be translated.\n"
        "3. **URL / link / path** — link targets, image paths, anchors, "
        "and query keys are byte-for-byte identical to the source. Only "
        "visible link text or human-readable URL path/query *values* may "
        "be translated.\n"
        "4. **Translatability gating** — first decide whether the SOURCE "
        "contains ANY human-readable prose (UI labels, messages, "
        "descriptions, alt text, comment text in code, user-facing string "
        "literals in code/data). If NONE exists (pure code, identifiers, "
        "URLs only), an output identical to the source MUST PASS — "
        "do not penalise an unchanged output for code-only or "
        "URL-only blocks.\n"
        "5. **Target-language requirement** — if the source contains "
        "translatable prose, that prose must be rendered in **{lang}** in "
        "the output (NOT left in the source language). Widely-adopted "
        "technical terms (API, SDK, GPU, Cookie) may remain in English "
        "where conventional in {lang}.\n"
        "6. **Format/template tokens** — printf-style specifiers "
        "(``%s`` / ``%d`` / ``%(name)s``), Handlebars/Mustache/Jinja "
        "double-brace templates (``{{name}}``), shell dollar-brace "
        "(``${{var}}``), and the opaque ``⟦P:N⟧`` placeholder "
        "tokens are byte-for-byte identical and appear the same number "
        "of times.\n"
        "7. **No invented content** — the output adds no new sentences, "
        "facts, or sections not present in the source.\n"
        "If ANY criterion fails, score \"no\" and put the SHORTEST useful "
        "reason in the ``reason`` field (one sentence). On PASS, the "
        "``reason`` field briefly states what looked good — it feeds "
        "intra-batch context for retries on sibling keys.\n"
    )

    VALIDATE_REFINE_CRITERIA = (
        "Source / output language: **{lang}** (refine is same-language).\n\n"
        "Criteria for a **'yes'** score (ALL must be satisfied):\n"
        "1. **Structural integrity** — every heading, list, table, "
        "link, blockquote, and fenced/inline code delimiter is preserved.\n"
        "2. **Code-block compliance** — inside fenced code blocks, "
        "code (logic, identifiers, order, formatting) is unchanged. Only "
        "comments and user-facing string literals may be polished. Inside "
        "inline code spans, the backticked content is preserved verbatim "
        "(identifiers, paths, UI labels, config values).\n"
        "3. **Language stability** — the output is in **{lang}**, the "
        "same language as the source. Refine is NOT translation; "
        "language switches are a fail.\n"
        "4. **Semantic preservation** — meaning, technical accuracy, "
        "and information content are identical to the source. No facts "
        "added, removed, or altered.\n"
        "5. **URL integrity** — URLs preserved; only obvious typos "
        "may be corrected.\n"
        "6. **Format/template tokens** — printf-style specifiers, "
        "double-brace templates, dollar-brace shell templates, and "
        "``⟦P:N⟧`` placeholder tokens are byte-for-byte "
        "identical and appear the same number of times.\n"
        "If ANY criterion fails, score \"no\" with the SHORTEST useful "
        "reason. On PASS, summarise briefly in ``reason`` for intra-batch "
        "retry context.\n"
    )

    RETRY_REASON_HEADER = "**PREVIOUS ATTEMPT REJECTED — REASONS:**"

    BATCH_REFINE_INSTRUCTION = (
        "Input is a JSON object where each key is an opaque block identifier and each value is a "
        "Markdown source fragment.\n"
        "Output a JSON object with EXACTLY the same set of keys as the input.\n\n"
        "Strict rules:\n"
        "1. Return ONLY a raw JSON object. The response MUST start with `{` and end with `}`. "
        "Do NOT wrap the JSON in Markdown code fences \u2014 no ```json, no ```, no surrounding "
        "backticks, no language tag. Do NOT include any prose, preamble, explanation, or "
        "epilogue before or after the JSON.\n"
        "2. Every input key MUST appear in the output exactly once — same order, same spelling.\n"
        "3. Do NOT add, omit, merge, or rename keys. Do NOT nest the object.\n"
        "4. Each value is the refined Markdown for that block, preserving original structure "
        "(headings, list bullets, table pipes, code fences, blockquote markers, inline code "
        "delimiters).\n"
        "5. Preserve the source language of each value — do not translate or switch languages.\n"
        "6. Improve clarity, grammar, punctuation, and sentence flow without changing meaning.\n"
        "7. Inside fenced code blocks, preserve the code itself verbatim: keep identifiers, "
        "function and variable names, module references, API paths, type names, and language "
        "syntax. You MAY polish grammar and wording in comments and user-facing string literals "
        "inside those code blocks \u2014 do not rewrite them into different statements.\n"
        "8. Inside inline code spans, preserve the content verbatim \u2014 identifiers, file "
        "paths, URLs, shell commands, UI labels, config values, and any other backticked "
        "fragment. Refine only polishes the surrounding prose; backticked fragments may name "
        "exact product strings that must keep matching the live product or API.\n"
        "9. Outside code contexts, keep bare URLs and file paths intact.\n"
        "10. Preserve format-string interpolation tokens (`{{name}}`, `%s`, `${{var}}`) exactly "
        "as they appear \u2014 altering them breaks runtime string formatting.\n"
        "11. Do not add or remove information; do not invent new content.\n"
        "12. Any opaque token of the form \u27e6P:N\u27e7 (where N is one or more decimal digits, "
        "e.g. \u27e6P:0\u27e7, \u27e6P:7\u27e7, \u27e6P:42\u27e7) is a placeholder for content "
        "that must NOT be altered. Copy every such token into the output exactly as-is \u2014 "
        "same characters, same digits, same count. Do not translate, renumber, split, remove, "
        "merge, or duplicate them.\n"
    )
